/**
 * Vanilla-Vite framework emitter (Layer 2).
 *
 * Produces a Vite project with plain JS/TS (no framework):
 *   package.json, vite.config.js, index.html,
 *   src/main.{js|ts}, src/style.css,
 *   src/lib/input.{js|ts} (if non-file input),
 *   src/lib/preprocess.{js|ts}, src/lib/inference.{js|ts},
 *   src/lib/postprocess.{js|ts}, README.md
 *
 * Uses ES modules with Vite dev server. No framework dependency.
 */

import type { ResolvedConfig } from '@webai/core';
import type { CodeBlock, GeneratedFile } from '../types.js';
import {
  emitDesignSystemCSS,
  emitAppCSS,
  addExports,
  findBlock,
  collectImports,
  emitReadme,
  getTaskLabel,
  getEngineLabel,
} from './shared.js';

const libExt = (config: ResolvedConfig) => (config.lang === 'ts' ? 'ts' : 'js');

function emitPackageJson(config: ResolvedConfig, blocks: CodeBlock[]): string {
  const deps: Record<string, string> = {};
  for (const imp of collectImports(blocks)) {
    if (imp === 'onnxruntime-web') deps[imp] = '^1.21.0';
    else deps[imp] = 'latest';
  }

  const devDeps: Record<string, string> = {
    vite: '^6.0.0',
  };
  if (config.lang === 'ts') {
    devDeps['typescript'] = '^5.7.0';
  }

  return JSON.stringify(
    {
      name: config.modelName,
      private: true,
      version: '0.0.0',
      type: 'module',
      scripts: {
        dev: 'vite',
        build: 'vite build',
        preview: 'vite preview',
      },
      dependencies: deps,
      devDependencies: devDeps,
    },
    null,
    2,
  );
}

function emitViteConfig(): string {
  return `import { defineConfig } from 'vite';

export default defineConfig({});
`;
}

function emitIndexHtml(config: ResolvedConfig): string {
  const taskLabel = getTaskLabel(config.task);
  const le = libExt(config);
  return `<!DOCTYPE html>
<html lang="en" data-theme="${config.theme}">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>${config.modelName} — ${taskLabel}</title>
    <link rel="stylesheet" href="/src/style.css" />
  </head>
  <body>
    <a href="#results" class="skip-link">Skip to results</a>
    <main>
      <h1>${config.modelName} — ${taskLabel}</h1>
      <div class="container">
        <div>
          <div class="drop-zone" id="dropZone" role="button" tabindex="0"
               aria-label="Drop an image here or click to browse for ${taskLabel.toLowerCase()}">
            <p>Drop an image here or click to browse</p>
            <p class="hint">Supports JPG, PNG, WebP</p>
            <input type="file" id="fileInput" accept="image/*" hidden>
          </div>
          <div id="preview" class="preview" hidden>
            <img id="previewImage" alt="Selected image for ${taskLabel.toLowerCase()}">
            <button id="changeBtn" class="change-btn">Choose another image</button>
          </div>
        </div>
        <div id="results" class="results" role="status" aria-live="polite" aria-atomic="true">
        </div>
      </div>
    </main>
    <aside class="status-bar">
      <span id="status">${config.modelName} · Loading...</span>
    </aside>
    <div class="footer">Generated by webai.js · ${config.modelName} · ${getEngineLabel(config.engine)}</div>
    <script type="module" src="/src/main.${le}"></script>
  </body>
</html>
`;
}

function emitMain(config: ResolvedConfig): string {
  const le = libExt(config);
  const t = config.lang === 'ts';

  return `import { createSession, runInference, getBackendLabel } from './lib/inference.${le}';
import { preprocessImage } from './lib/preprocess.${le}';
import { postprocessResults } from './lib/postprocess.${le}';
import './style.css';

const MODEL_PATH = '/${config.modelName}.onnx';
let session${t ? ': Awaited<ReturnType<typeof createSession>> | null' : ''} = null;

function updateStatus(text${t ? ': string' : ''}) {
  document.getElementById('status')${t ? '!' : ''}.textContent = text;
}

async function init() {
  updateStatus('Loading model...');
  try {
    session = await createSession(MODEL_PATH);
    updateStatus('${config.modelName} \\u00b7 Ready');
  } catch (e) {
    updateStatus('Failed to load model');
    console.error('Model load error:', e);
  }
}

const dropZone = document.getElementById('dropZone')${t ? '!' : ''};
const fileInput = document.getElementById('fileInput') as ${t ? 'HTMLInputElement' : 'any'};
const preview = document.getElementById('preview')${t ? '!' : ''};
const previewImage = document.getElementById('previewImage') as ${t ? 'HTMLImageElement' : 'any'};
const resultsDiv = document.getElementById('results')${t ? '!' : ''};
const changeBtn = document.getElementById('changeBtn')${t ? '!' : ''};

dropZone.addEventListener('click', () => fileInput.click());
dropZone.addEventListener('keydown', (e${t ? ': KeyboardEvent' : ''}) => {
  if (e.key === 'Enter' || e.key === ' ') { e.preventDefault(); fileInput.click(); }
});
dropZone.addEventListener('dragover', (e${t ? ': DragEvent' : ''}) => { e.preventDefault(); dropZone.classList.add('drag-over'); });
dropZone.addEventListener('dragleave', () => { dropZone.classList.remove('drag-over'); });
dropZone.addEventListener('drop', (e${t ? ': DragEvent' : ''}) => {
  e.preventDefault(); dropZone.classList.remove('drag-over');
  const file = e.dataTransfer${t ? '!' : ''}.files[0];
  if (file) handleFile(file);
});
fileInput.addEventListener('change', () => {
  const file = fileInput.files${t ? '!' : ''}[0];
  if (file) handleFile(file);
});
changeBtn.addEventListener('click', () => {
  preview.hidden = true; dropZone.hidden = false;
  resultsDiv.innerHTML = ''; fileInput.value = '';
});

async function handleFile(file${t ? ': File' : ''}) {
  if (!file.type.startsWith('image/')) {
    resultsDiv.textContent = 'Unsupported file type. Try JPG, PNG, or WebP.';
    return;
  }

  const url = URL.createObjectURL(file);
  previewImage.src = url;
  preview.hidden = false;
  dropZone.hidden = true;

  await new Promise((resolve) => { previewImage.onload = resolve; });

  const canvas = document.createElement('canvas');
  canvas.width = previewImage.naturalWidth;
  canvas.height = previewImage.naturalHeight;
  const ctx = canvas.getContext('2d')${t ? '!' : ''};
  ctx.drawImage(previewImage, 0, 0);
  const imageData = ctx.getImageData(0, 0, canvas.width, canvas.height);

  if (!session) { resultsDiv.textContent = 'Model not loaded yet.'; return; }

  updateStatus('${config.modelName} \\u00b7 Processing...');
  const start = performance.now();

  const inputTensor = preprocessImage(imageData.data, canvas.width, canvas.height);
  const output = await runInference(session, inputTensor);
  const results = postprocessResults(output);

  const elapsed = (performance.now() - start).toFixed(1);
  updateStatus(\`${config.modelName} \\u00b7 \${elapsed}ms \\u00b7 \${getBackendLabel(session)}\`);

  renderResults(results);
  URL.revokeObjectURL(url);
}

function renderResults(results${t ? ': { indices: number[]; values: number[] }' : ''}) {
  resultsDiv.innerHTML = '';
  const maxValue = results.values[0] || 1;

  for (let i = 0; i < results.indices.length; i++) {
    const pct = (results.values[i] * 100).toFixed(1);
    if (results.values[i] < 0.01) continue;

    const row = document.createElement('div');
    row.className = 'result-row' + (i === 0 ? ' top-result' : '');
    row.setAttribute('tabindex', '0');
    row.setAttribute('aria-label', \`Class \${results.indices[i]}: \${pct} percent\`);

    row.innerHTML =
      '<span class="result-label">Class ' + results.indices[i] + '</span>' +
      '<div class="result-bar-container"><div class="result-bar" style="width:' +
      ((results.values[i] / maxValue) * 100) + '%"></div></div>' +
      '<span class="result-pct">' + pct + '%</span>';

    resultsDiv.appendChild(row);
  }
}

init();
`;
}

function emitStyleCss(config: ResolvedConfig): string {
  return `${emitDesignSystemCSS(config)}\n\n${emitAppCSS()}`;
}

/** Wrap a CodeBlock's code with exports for use as a lib module */
function toLibModule(block: CodeBlock | undefined): string {
  if (!block) return '';
  return addExports(block.code, block.exports);
}

/**
 * Emit Vanilla-Vite framework files.
 */
export function emitVanillaVite(config: ResolvedConfig, blocks: CodeBlock[]): GeneratedFile[] {
  const le = libExt(config);

  const inputBlock = findBlock(blocks, 'input');
  const preprocessBlock = findBlock(blocks, 'preprocess');
  const inferenceBlock = findBlock(blocks, 'inference');
  const postprocessBlock = findBlock(blocks, 'postprocess');

  const filePaths: string[] = [
    'package.json',
    'vite.config.js',
    'index.html',
    `src/main.${le}`,
    'src/style.css',
  ];

  if (inputBlock?.code) {
    filePaths.push(`src/lib/input.${le}`);
  }

  filePaths.push(
    `src/lib/preprocess.${le}`,
    `src/lib/inference.${le}`,
    `src/lib/postprocess.${le}`,
    'README.md',
  );

  const files: GeneratedFile[] = [
    { path: 'package.json', content: emitPackageJson(config, blocks) },
    { path: 'vite.config.js', content: emitViteConfig() },
    { path: 'index.html', content: emitIndexHtml(config) },
    { path: `src/main.${le}`, content: emitMain(config) },
    { path: 'src/style.css', content: emitStyleCss(config) },
  ];

  if (inputBlock?.code) {
    files.push({ path: `src/lib/input.${le}`, content: toLibModule(inputBlock) });
  }

  files.push(
    { path: `src/lib/preprocess.${le}`, content: toLibModule(preprocessBlock) },
    { path: `src/lib/inference.${le}`, content: toLibModule(inferenceBlock) },
    { path: `src/lib/postprocess.${le}`, content: toLibModule(postprocessBlock) },
    { path: 'README.md', content: emitReadme(config, filePaths) },
  );

  return files;
}
